# Generated by Django 4.0 on 2022-03-07 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadTagsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strEPC', models.CharField(max_length=100)),
                ('antenna', models.IntegerField()),
                ('strRSSI', models.CharField(max_length=100)),
                ('nReadCount', models.IntegerField()),
                ('readtagorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagsApp.readtagsorder')),
            ],
        ),
    ]
